In [1]:
import numpy as py
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data=pd.read_csv("mushroom.csv")

In [3]:
data.head()

poisonous cap-shape cap-surface cap-color bruises odor gill-attachment  \
0         p         x           s         n       t    p               f   
1         e         x           s         y       t    a               f   
2         e         b           s         w       t    l               f   
3         p         x           y         w       t    p               f   
4         e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
poisonous                   8124 non-null object
cap-shape                   8124 non-null object
cap-surface                 8124 non-null object
cap-color                   8124 non-null object
bruises                     8124 non-null object
odor                        8124 non-null object
gill-attachment             8124 non-null object
gill-spacing                8124 non-null object
gill-size                   8124 non-null object
gill-color                  8124 non-null object
stalk-shape                 8124 non-null object
stalk-root                  8124 non-null object
stalk-surface-above-ring    8124 non-null object
stalk-surface-below-ring    8124 non-null object
stalk-color-above-ring      8124 non-null object
stalk-color-below-ring      8124 non-null object
veil-type                   8124 non-null object
veil-color                  8124 non-null object
ring-number

In [5]:
data.describe()

poisonous cap-shape cap-surface cap-color bruises  odor  \
count       8124      8124        8124      8124    8124  8124   
unique         2         6           4        10       2     9   
top            e         x           y         n       f     n   
freq        4208      3656        3244      2284    4748  3528   

       gill-attachment gill-spacing gill-size gill-color   ...    \
count             8124         8124      8124       8124   ...     
unique               2            2         2         12   ...     
top                  f            c         b          b   ...     
freq              7914         6812      5612       1728   ...     

       stalk-surface-below-ring stalk-color-above-ring stalk-color-below-ring  \
count                      8124                   8124                   8124   
unique                        4                      9                      9   
top                           s                      w                      w   
freq                       4936                   4464                   4384   

       veil-type veil-color ring-number ring-type spore-print-color  \
count       8124       8124        8124      8124              8124   
unique         1          4           3         5                 9   
top            p          w           o         p                 w   
freq        8124       7924        7488      3968              2388   

       population habitat  
count        8124    8124  
unique          6       7  
top             v       d  
freq         4040    3148  

[4 rows x 23 columns]

In [6]:
y=data['poisonous']

In [7]:
X=data.iloc[:,1:]

In [8]:
data.iloc[:,0:1]

poisonous
0            p
1            e
2            e
3            p
4            e
5            e
6            e
7            e
8            p
9            e
10           e
11           e
12           e
13           p
14           e
15           e
16           e
17           p
18           p
19           p
20           e
21           p
22           e
23           e
24           e
25           p
26           e
27           e
28           e
29           e
...        ...
8094         e
8095         p
8096         e
8097         p
8098         p
8099         e
8100         e
8101         p
8102         e
8103         e
8104         e
8105         e
8106         e
8107         e
8108         p
8109         e
8110         e
8111         e
8112         e
8113         p
8114         p
8115         e
8116         p
8117         p
8118         p
8119         e
8120         e
8121         e
8122         p
8123         e

[8124 rows x 1 columns]

In [9]:
y.value_counts()

e    4208
p    3916
Name: poisonous, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
model= DecisionTreeClassifier()

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=0, test_size=0.3)

## LabelEncoder

In [14]:
data=pd.read_csv("mushroom.csv")

In [15]:
from sklearn.preprocessing import LabelEncoder

### LabelEncoder 연습

In [16]:
le=LabelEncoder()

In [17]:
le.fit([1,2,2,6])

LabelEncoder()

In [18]:
le.classes_

array([1, 2, 6])

In [19]:
le.transform([1,1,2,6])   #1126어래이를 트렌스하겠다. 그럼 0012가된다.

array([0, 0, 1, 2], dtype=int64)

In [20]:
le.inverse_transform([0,0,1,2])  # 어래이0012를 다시돌리겠다. 

array([1, 1, 2, 6])

In [21]:
le.fit(["a","f","c","e","A"])

LabelEncoder()

In [22]:
le.classes_

array(['A', 'a', 'c', 'e', 'f'],
      dtype='<U1')

In [23]:
le.transform(["a","f","c","e","A"])

array([1, 4, 2, 3, 0], dtype=int64)

In [24]:
le.fit_transform(["a","f","c","e","A"])

array([1, 4, 2, 3, 0], dtype=int64)

In [25]:
label_encoder=LabelEncoder()

In [26]:
for col in data.columns:
    data[col]=label_encoder.fit_transform(data[col])

In [27]:
label_encoder.classes_

array(['d', 'g', 'l', 'm', 'p', 'u', 'w'], dtype=object)

In [28]:
len(data.columns)

23

In [29]:
data

poisonous  cap-shape  cap-surface  cap-color  bruises  odor  \
0             1          5            2          4        1     6   
1             0          5            2          9        1     0   
2             0          0            2          8        1     3   
3             1          5            3          8        1     6   
4             0          5            2          3        0     5   
5             0          5            3          9        1     0   
6             0          0            2          8        1     0   
7             0          0            3          8        1     3   
8             1          5            3          8        1     6   
9             0          0            2          9        1     0   
10            0          5            3          9        1     3   
11            0          5            3          9        1     0   
12            0          0            2          9        1     0   
13            1          5            3          8        1     6   
14            0          5            0          4        0     5   
15            0          4            0          3        0     5   
16            0          2            0          8        0     5   
17            1          5            2          4        1     6   
18            1          5            3          8        1     6   
19            1          5            2          4        1     6   
20            0          0            2          9        1     0   
21            1          5            3          4        1     6   
22            0          0            3          9        1     3   
23            0          0            3          8        1     0   
24            0          0            2          8        1     3   
25            1          2            2          8        1     6   
26            0          5            3          9        1     0   
27            0          5            3          8        1     3   
28            0          2            0          4        0     5   
29            0          5            2          9        1     0   
...         ...        ...          ...        ...      ...   ...   
8094          0          0            2          3        0     5   
8095          1          5            3          1        0     4   
8096          0          3            0          8        0     5   
8097          1          3            3          4        0     7   
8098          1          3            2          2        0     8   
8099          0          3            0          8        0     5   
8100          0          2            2          4        0     5   
8101          1          3            2          2        0     7   
8102          0          5            2          4        0     5   
8103          0          3            2          4        0     5   
8104          0          3            2          4        0     5   
8105          0          3            2          4        0     5   
8106          0          3            2          4        0     5   
8107          0          5            2          4        0     5   
8108          1          3            3          2        0     8   
8109          0          0            2          8        0     5   
8110          0          5            2          4        0     5   
8111          0          3            2          8        0     5   
8112          0          3            2          4        0     5   
8113          1          3            3          2        0     8   
8114          1          2            3          1        0     4   
8115          0          5            2          4        0     5   
8116          1          3            3          4        0     7   
8117          1          3            2          2        0     8   
8118          1          3            3          4        0     2   
8119          0          3            2          4        0     5   
8120

### 실습)선형모델,Decisiontree실습

In [30]:
X=data.iloc[:,1:] 
y=data.iloc[:,0]

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=0, test_size=0.3)

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

In [33]:
for c in [0.001,0.01,0.1,1,10,100,1000]:
    svc=LinearSVC(C=c)
    svc.fit(X_train,y_train)
    print(c)
    print(svc.score(X_train,y_train))
    print(svc.score(X_test,y_test))

0.001
0.914175167077
0.917965545529
0.01
0.943193809356
0.94257588187
0.1
0.946007738305
0.944626743232
1
0.950052761168
0.947087776866
10
0.943897291593
0.936833470057
100
0.925782623989
0.923707957342
1000
0.954449525149
0.950779327317


In [34]:
svc=LinearSVC(C=1)
svc.fit(X_train,y_train)
print(svc.score(X_test,y_test))

0.93560295324


In [35]:
tree =DecisionTreeClassifier(random_state=0)
tree.fit(X_train,y_train)
print(tree.score(X_train,y_train))
print(tree.score(X_test,y_test))

1.0
1.0


In [36]:
tree =DecisionTreeClassifier(random_state=0, max_depth=7)
tree.fit(X_train,y_train)
print(tree.score(X_train,y_train))
print(tree.score(X_test,y_test))

1.0
1.0


# one-hot-encoding 

In [37]:
data=pd.read_csv("mushroom.csv")

In [38]:
pd.get_dummies(data.loc[:,"cap-shape"],prefix="cap-shape")

cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0               0            0            0            0            0   
1               0            0            0            0            0   
2               1            0            0            0            0   
3               0            0            0            0            0   
4               0            0            0            0            0   
5               0            0            0            0            0   
6               1            0            0            0            0   
7               1            0            0            0            0   
8               0            0            0            0            0   
9               1            0            0            0            0   
10              0            0            0            0            0   
11              0            0            0            0            0   
12              1            0            0            0            0   
13              0            0            0            0            0   
14              0            0            0            0            0   
15              0            0            0            0            1   
16              0            0            1            0            0   
17              0            0            0            0            0   
18              0            0            0            0            0   
19              0            0            0            0            0   
20              1            0            0            0            0   
21              0            0            0            0            0   
22              1            0            0            0            0   
23              1            0            0            0            0   
24              1            0            0            0            0   
25              0            0            1            0            0   
26              0            0            0            0            0   
27              0            0            0            0            0   
28              0            0            1            0            0   
29              0            0            0            0            0   
...           ...          ...          ...          ...          ...   
8094            1            0            0            0            0   
8095            0            0            0            0            0   
8096            0            0            0            1            0   
8097            0            0            0            1            0   
8098            0            0            0            1            0   
8099            0            0            0            1            0   
8100            0            0            1            0            0   
8101            0            0            0            1            0   
8102            0            0            0            0            0   
8103            0            0            0            1            0   
8104            0            0            0            1            0   
8105            0            0            0            1            0   
8106            0            0            0            1            0   
8107            0            0            0            0            0   
8108            0            0            0            1            0   
8109            1            0            0            0            0   
8110            0            0            0            0            0   
8111            0            0            0            1            0   
8112            0            0            0            1            0   
8113            0            0            0            1            0   
8114            0            0            1            0            0   
8115            0            0            0            0            0   
8116            0            0            0            1        

In [39]:
X=data.iloc[:,1:]
y=data.iloc[:,0]

In [40]:
dic= {"p":0,"e":1}
y=y.map(dic)
y

0       0
1       1
2       1
3       0
4       1
5       1
6       1
7       1
8       0
9       1
10      1
11      1
12      1
13      0
14      1
15      1
16      1
17      0
18      0
19      0
20      1
21      0
22      1
23      1
24      1
25      0
26      1
27      1
28      1
29      1
       ..
8094    1
8095    0
8096    1
8097    0
8098    0
8099    1
8100    1
8101    0
8102    1
8103    1
8104    1
8105    1
8106    1
8107    1
8108    0
8109    1
8110    1
8111    1
8112    1
8113    0
8114    0
8115    1
8116    0
8117    0
8118    0
8119    1
8120    1
8121    1
8122    0
8123    1
Name: poisonous, Length: 8124, dtype: int64

In [41]:
X=pd.get_dummies(X,prefix=X.columns)

In [42]:
X.head(2)

cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0            0            0            0            0            0   
1            0            0            0            0            0   

   cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  cap-surface_y  \
0            1              0              0              1              0   
1            1              0              0              1              0   

     ...      population_s  population_v  population_y  habitat_d  habitat_g  \
0    ...                 1             0             0          0          0   
1    ...                 0             0             0          0          1   

   habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0          0          0          0          1          0  
1          0          0          0          0          0  

[2 rows x 117 columns]

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=0, test_size=0.3)

In [44]:
svc=LinearSVC(C=1)
svc.fit(X_train,y_train)
print(svc.score(X_train,y_train))
print(svc.score(X_test,y_test))

1.0
1.0


In [45]:
Logistic=LogisticRegression()
Logistic.fit(X_train,y_train)
print(Logistic.score(X_train,y_train))
print(Logistic.score(X_test,y_test))

1.0
1.0


In [46]:
tree =DecisionTreeClassifier(random_state=0)
tree.fit(X_train,y_train)
print(tree.score(X_train,y_train))
print(tree.score(X_test,y_test))

1.0
1.0


# RandomForest

In [47]:
from sklearn.ensemble import  RandomForestClassifier, GradientBoostingClassifier

In [48]:
model = RandomForestClassifier(n_estimators=30,max_depth=10, random_state=7)

In [49]:
model.fit(X_train,y_train)
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

1.0
1.0


In [50]:
import_list=list(zip(model.feature_importances_,X_train.columns))
import_list.sort()
import_list.reverse()

In [51]:
import_list[:5]

[(0.098034740513068416, 'odor_n'),
 (0.075922445041416792, 'spore-print-color_h'),
 (0.072741699445539043, 'gill-size_b'),
 (0.067531978827498715, 'stalk-surface-below-ring_k'),
 (0.053500549772027131, 'odor_f')]

Index(['cap-shape_b', 'cap-shape_c', 'cap-shape_f', 'cap-shape_k',
       'cap-shape_s', 'cap-shape_x', 'cap-surface_f', 'cap-surface_g',
       'cap-surface_s', 'cap-surface_y',
       ...
       'population_s', 'population_v', 'population_y', 'habitat_d',
       'habitat_g', 'habitat_l', 'habitat_m', 'habitat_p', 'habitat_u',
       'habitat_w'],
      dtype='object', length=117)

In [52]:
model.feature_importances_

array([  2.52510643e-03,   3.44228358e-04,   3.15955124e-04,
         1.60371571e-04,   1.11118569e-03,   1.24002786e-03,
         8.30059400e-03,   9.04515863e-05,   3.14331784e-03,
         2.91347398e-03,   3.55704038e-03,   5.35352258e-04,
         6.69258207e-04,   1.91935150e-03,   9.61024478e-05,
         1.79374158e-03,   0.00000000e+00,   0.00000000e+00,
         8.62548893e-04,   2.84772436e-03,   1.63051325e-02,
         2.79431423e-02,   6.25469624e-03,   1.02163364e-02,
         5.35005498e-02,   9.56252878e-03,   0.00000000e+00,
         9.80347405e-02,   2.36725978e-02,   1.97536379e-03,
         5.60962116e-03,   4.02191671e-04,   1.19282519e-04,
         1.79830678e-02,   1.15580471e-02,   7.27416994e-02,
         2.73298717e-02,   4.76161096e-02,   0.00000000e+00,
         5.28380233e-04,   1.72688664e-03,   3.46920622e-05,
         4.70675257e-05,   0.00000000e+00,   6.95336352e-05,
         4.26803052e-04,   1.61121545e-04,   4.48310337e-03,
         5.66039539e-05,

In [58]:
for z,o in zip(data.iloc[:,0],data.iloc[:,1]):
    print(z,o)

p x
e x
e b
p x
e x
e x
e b
e b
p x
e b
e x
e x
e b
p x
e x
e s
e f
p x
p x
p x
e b
p x
e b
e b
e b
p f
e x
e x
e f
e x
e b
p x
e x
e x
e b
e x
e s
p x
e x
e b
e b
e x
e x
p x
e x
e x
e x
e x
e x
e f
e x
e x
e b
p x
p x
e b
e f
e b
e x
e x
e s
e b
e b
e b
e b
e f
e x
e f
e x
e x
e f
e b
e f
e x
e b
e f
e x
e f
p x
e f
e x
p x
e f
e x
e x
e x
e b
e x
e f
e s
e x
e b
e x
e x
e x
e x
e f
e x
e b
e x
e x
e b
e f
e x
e b
e x
e x
e b
e b
e x
e x
e s
e x
e x
p x
e x
e s
e x
e x
e s
p x
e x
p f
e f
e x
e x
e b
e f
e x
e b
e b
e b
e f
e x
e f
p x
e f
e x
p x
e b
e x
e b
e s
e f
e x
e x
e f
e x
e b
e b
e x
e x
e x
e s
e x
e x
e b
e x
e b
e b
e b
e b
e x
e f
e x
e f
e b
e b
e x
e b
e x
e b
e x
e b
e f
e b
e b
e b
e x
e b
p x
e s
e f
e x
e f
p x
e b
e f
e b
e x
e x
e x
e b
e f
e x
e f
e b
e x
e x
e f
e x
e b
e x
e x
e f
p x
e b
e b
e b
e b
e x
e b
e x
e x
e f
e b
e x
e x
e x
e s
e x
p x
e x
e f
e x
e b
e x
e x
p x
e b
e x
p x
e x
e f
e b
e x
e x
e b
e x
e f
e f
e x
e x
p x
e f
e x
e x
e x
e f
e x


e x
e x
e x
e f
p f
e f
e x
e x
e x
e x
p f
e f
e x
e f
e x
e x
e x
p x
e x
e x
e f
e x
e x
e x
e f
e x
e f
e f
e f
e f
e x
e x
p f
e x
e x
e b
e x
e f
e x
e f
e x
p x
e x
e x
e f
e x
e x
e f
e x
e f
e x
e x
e f
e x
e x
p x
e x
e x
e x
e x
e x
e x
e x
e x
e f
e f
e x
e f
e x
e x
e x
p x
p f
e x
e x
e x
e f
e x
e x
e x
e x
e x
e x
e x
e x
e x
e x
e f
e f
e x
p f
e f
p x
e x
e f
e x
e f
e x
e x
e x
e f
e f
e x
e x
e x
e f
e x
e f
e x
e x
e x
e x
e x
e x
e x
e f
e x
e x
e f
e f
e x
p x
e x
e x
e x
e f
e x
e f
e f
e f
e x
e x
e x
e x
e x
e x
e x
e f
e x
e f
e x
e x
e f
e x
e x
e f
e f
e x
e x
e x
e x
e f
e x
p x
e x
e f
e x
e f
e x
e x
e f
e x
e x
e x
e f
e x
e x
e f
e x
e x
e x
e x
e x
e x
e x
e x
e f
e f
e x
e x
e f
p x
e x
e x
p f
e f
e x
e x
e x
e x
e x
e x
e f
e x
e f
e f
e f
e x
e f
e f
e x
e x
e x
e f
e x
e f
e x
e x
e x
e f
e x
e x
e x
e f
e f
e f
e x
e f
e x
e x
e x
e x
e f
e x
e x
e x
e f
e x
p x
e f
e f
p f
e x
e x
e x
e x
e x
e x
e f
e x
e x
e x
e x
e x
e x
e x
e x
e x
e x
e f


p f
p x
p x
p x
p f
p f
p f
p x
p x
p x
p x
p x
p f
p f
p x
p f
p x
p x
p x
p f
p f
p f
p x
p f
p x
p x
p x
e k
e f
p x
p f
p x
p f
p x
p f
p x
p x
p x
p x
p f
p x
p f
p f
p x
p f
e x
e x
p x
p f
p x
p x
p f
p f
p f
e f
p x
p f
p f
p x
p x
p k
p f
e k
p f
p f
p x
p x
p f
p f
p x
p f
p x
p b
e k
p x
p x
e k
p f
p x
p x
p x
p x
p f
p x
e f
p x
p f
p f
e f
p x
p x
p x
e k
p x
p x
p f
p f
e k
p x
p f
p f
p c
p x
p b
p x
p f
p b
p x
p x
e k
e k
p f
p f
p f
p x
p f
p x
p x
p f
e x
p x
p x
p x
e f
p x
e x
e f
p f
p f
p x
p x
p x
p x
p f
p f
p x
p x
p f
e x
p f
p f
e k
p x
p x
e x
p x
p f
p f
p f
p f
e x
e f
p b
e x
e f
p x
p x
p f
p x
p x
e f
p x
p f
e x
p x
p f
p f
p x
e k
p x
p x
p f
e k
p x
p f
p f
p x
p x
p x
p f
p f
e k
p f
p x
p x
e f
p x
p x
p x
p x
p f
e k
p x
p x
e k
p f
e x
p f
e x
p b
p f
p x
p x
p x
p x
e k
e k
p x
e x
p f
p f
p f
p k
e k
p k
p f
p f
p f
e k
p f
p x
p x
p x
p b
p f
p x
p x
e k
p f
p x
p b
p x
e k
p f
p x
p f
p f
p k
p f
e f
p x
p x
p x
p x
e k
p f
e x
p f
e k
p x


p k
p k
p k
p k
p k
e f
p f
p k
e x
e x
p k
e x
p k
p k
p k
p k
p k
e b
e f
e b
p k
e x
p k
e b
e b
p x
e x
e x
e x
e k
e x
p f
e x
p k
p k
e x
e k
e b
e k
p k
p f
p k
e k
e f
p k
e b
p k
e k
p k
p k
e f
p k
p k
e x
e x
e x
e x
p k
p k
e x
p k
e x
p k
p f
p k
e k
p k
p k
e b
p k
p k
e k
p k
p k
p k
p k
e k
p k
p k
e b
e x
e b
p k
p k
p k
e b
p f
p k
e k
p k
p k
p k
e x
p k
p k
p b
p k
e x
p k
e k
p k
p k
p k
p k
e x
e b
p k
e b
p k
p k
e b
p k
e b
p f
p k
p k
p k
e b
e k
p k
p f
e x
e x
p k
p k
e k
e b
e x
p f
p k
p x
e f
p k
p x
p k
e b
e b
e k
e k
e x
p k
p f
p k
p f
e b
e k
e b
e f
p k
p k
p k
p f
p x
e f
e k
p k
p x
e b
p k
e b
e f
p k
p k
p k
p k
p k
e x
p k
e f
e b
p k
p k
p k
e b
p k
e b
p k
e x
p k
p k
e x
p k
p k
e k
e k
p k
p k
e k
p k
p k
p k
p k
p k
e k
e b
p k
e f
e f
p k
e f
e x
p c
p k
p k
p k
e b
p k
e x
p x
p x
p f
e k
e b
p f
p k
e b
e x
p f
e k
e b
e x
p k
p x
p k
e x
p k
p x
p k
p k
p k
p k
e b
e k
p k
p k
e k
e x
p k
e k
e k
e f
e x
e b
e x
e k
p k
p k
e k
e x
p k


In [55]:
model =GradientBoostingClassifier(n_estimators=50)

In [56]:
model.fit(X_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=50,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [57]:
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

0.999648258881
0.999589827728


In [60]:
!python --version

Python 3.6.3 :: Anaconda, Inc.


In [61]:
!pip install xgboost-0.90-cp36-cp36m-win_amd64.whl

Processing c:\users\pc-23\python수업\xgboost-0.90-cp36-cp36m-win_amd64.whl


You are using pip version 9.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [62]:
from xgboost import XGBRFClassifier

In [63]:
xgb= XGBRFClassifier()

In [64]:
xgb.fit(X_train,y_train)

XGBRFClassifier(base_score=0.5, colsample_bylevel=1, colsample_bynode=0.8,
        colsample_bytree=1, gamma=0, learning_rate=1, max_delta_step=0,
        max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
        n_jobs=1, nthread=None, objective='binary:logistic',
        random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
        seed=None, silent=None, subsample=0.8, verbosity=1)

In [65]:
print(xgb.score(X_train,y_train))
print(xgb.score(X_test,y_test))

0.98786493141
0.985643970468


In [1]:
svc=LinearSVC(C=1)
svc.fit(X_train,y_train)
print(svc.score(X_train,y_train))
print(svc.score(X_test,y_test))

NameError: name 'LinearSVC' is not defined